General:
    comment:
    seed: 2021
    fp16: True
    amp_level: O1
    precision: 16
    multi_gpu_mode: dp
    gpus: [0]
    epochs: &epoch 200
    grad_acc: 2
    frozen_bn: False
    patience: 10
    server: test
    log_path: logs/

Data:
    dataset_name: camel_data
    data_shuffle: False
    data_dir: /data/scratch/DBI/DUDBI/DYNCESYS/OlgaF/ovarian_cancer/tf_features/pt_files/
    label_dir: dataset_csv/ovarian/
    fold: 0
    nfold: 1

    train_dataloader:
        batch_size: 1
        num_workers: 8

    test_dataloader:
        batch_size: 1
        num_workers: 8

Model:
    name: TransMIL
    n_classes: 2

Optimizer:
    opt: lookahead_radam
    lr: 0.0002
    opt_eps: null
    opt_betas: null
    momentum: null
    weight_decay: 0.00001

Loss:
    base_loss: CrossEntropyLoss

#/run/user/1001/gvfs/smb-share:server=rds.icr.ac.uk,share=data/DBI/DUDBI/DYNCESYS/OlgaF/camelyon_data/camelyon_features/tumor_vs_normal_resnet_features/pt_files/
